# https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml

global:
  postgresql:
    auth:
      postgresPassword: "${postgresPassword}"

primary:
  persistence:
    storageClass: "${storageclass}"
    size: 1Gi