apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-cert
  namespace: ${namespace}
spec:
  secretName: rabbitmq-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: rabbitmq-cert
  dnsNames:
  - 'rabbitmq.infrastructure.${domain-name}'
