apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: consul
spec:
  destination:
    namespace: consul
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: src/argocd/infrastructure/base/
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
