apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identityserver4-admin
  namespace: argocd
spec:
  destination:
    namespace: identityserver4
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: src/argocd/infrastructure/base/identityserver4-admin
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
