apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kafka
  namespace: ${namespace}
spec:
  entryPoints:
    - kafka
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - name: kafka
      port: 9092

