apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres
  namespace: ${namespace}
spec:
  entryPoints:
    - postgres
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - name: postgres-postgresql
      port: 5432
