apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-cert
  namespace: ${namespace}
spec:
  secretName: postgres-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: postgres-cert
  dnsNames:
  - 'postgres.infrastructure.${domain-name}'
