site_name: K8S Dev Infrastructure
extra_css: [stylesheets/extra.css]
theme:
  name: material
  features:
    - content.tabs.link
nav:
    - Home: index.md
    - Preparation: preparation.md
    - Clusters:
      - 'K3S with terraform': ./clusters/k3s.md
      - 'KinD with terraform': ./clusters/kind.md
      - 'Docker Desktop': ./clusters/desktop-cluster.md
      - 'Rancher Desktop': ./clusters/rancher-cluster.md
      - 'Minikube': ./clusters/minikube-cluster.md
    - Install: ./installation-terraform.md
    - Terraform Specs:
      - Main: ./terraform-specs.md
      - Modules: specs/
    - About:
        - 'License': license.md
dev_addr: '0.0.0.0:8080'

plugins:
  - include_dir_to_nav

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format