site_name: K8S Dev Infrastructure
theme:
  name: material
  features:
    - content.tabs.link
nav:
    - Home: 'index.md'
    - Preparation: './preparation.md'
    - Install: './installation-terraform.md'
    - About:
        - 'License': 'license.md'
dev_addr: '0.0.0.0:8080'

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true