[rules]
    skip-rules = [
        "AC_K8S_0002", # TLS termination happens on reverse proxy
        # "AC_K8S_0064",
        "AC_K8S_0068",
        "AC_K8S_0069",
        "AC_K8S_0070",
        "AC_K8S_0072",
        "AC_K8S_0073",
        "AC_K8S_0079",
        "AC_K8S_0080"
    ]