apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-cert
  namespace: ${namespace}
spec:
  secretName: jaeger-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: jaeger-cert
  dnsNames:
  - 'jaeger.infrastructure.${domain-name}'
