apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: goldilocks-cert
  namespace: ${namespace}
spec:
  secretName: goldilocks-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: goldilocks-cert
  dnsNames:
  - 'goldilocks.infrastructure.${domain-name}'
