apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mariadb
  namespace: ${namespace}
spec:
  entryPoints:
    - mariadb
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - name: mariadb
      port: 3306
