apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb-cert
  namespace: ${namespace}
spec:
  secretName: mariadb-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: mariadb-cert
  dnsNames:
  - 'mariadb.infrastructure.${domain-name}'
