server:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http@kubernetescrd
    labels: {}
    hosts:
      - argo.k8s.local
    paths:
      - /
    extraPaths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
    tls:
      - secretName: argocd-tls-certificate
        hosts:
          - argo.k8s.local
    https: true
  ingressGrpc:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http@kubernetescrd
    labels: {}
    hosts:
      - argo.k8s.local
    paths:
      - /
    extraPaths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
    tls:
      - secretName: argocd-tls-certificate
        hosts:
          - argo.k8s.local
    https: true
  extraArgs: []
    # - --insecure
  certificate:
    enabled: true
    domain: argo.k8s.local
    issuer:
      kind: ClusterIssuer
      name: selfsigned-ca-issuer
    additionalHosts: []
    secretName: argocd-tls-certificate
  config:
    url: https://argo.k8s.local
    resource.customizations: |
      networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
      extensions/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
      jaegertracing.io/Jaeger:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
      admissionregistration.k8s.io/ValidatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/1/clientConfig/caBundle
          - /webhooks/2/clientConfig/caBundle
          - /webhooks/3/clientConfig/caBundle
          - /webhooks/4/clientConfig/caBundle
          - /webhooks/5/clientConfig/caBundle
          - /webhooks/6/clientConfig/caBundle
          - /webhooks/7/clientConfig/caBundle
          - /webhooks/8/clientConfig/caBundle
          - /webhooks/9/clientConfig/caBundle
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/1/clientConfig/caBundle
          - /webhooks/2/clientConfig/caBundle
          - /webhooks/3/clientConfig/caBundle
          - /webhooks/4/clientConfig/caBundle
          - /webhooks/5/clientConfig/caBundle
          - /webhooks/6/clientConfig/caBundle
          - /webhooks/7/clientConfig/caBundle