apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic-kb
  namespace: ${namespace}
spec:
  version: 7.12.1
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef: # This connection does not go through the mesh
    name: elastic-es
  # config:
  #   elasticsearch.hosts:
  #     - http://127.0.0.1:9200
  #   elasticsearch.username: elastic
  #   elasticsearch.ssl.verificationMode: none
  podTemplate:

    spec:
      automountServiceAccountToken: true
      serviceAccount: elastic-kb
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
          # - name: ELASTICSEARCH_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: elastic-es-es-elastic-user
          #       key: elastic
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 1Gi
            cpu: 1