apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-forward-cert
  namespace: ${namespace}
spec:
  secretName: auth-forward-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: auth-forward-cert
  dnsNames:
  - 'auth.${domain-name}'
