apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-cert
  namespace: ${namespace}
spec:
  secretName: registry-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: registry-cert
  dnsNames:
  - 'registry.infrastructure.${domain-name}'
