vpa:
  # vpa.enabled -- If true, the vpa will be installed as a sub-chart
  enabled: false
  updater:
    enabled: false

metrics-server:
  # metrics-server.enabled -- If true, the metrics-server will be installed as a sub-chart
  enabled: false
  apiService:
    create: true

image:
  pullPolicy: IfNotPresent

dashboard:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http@kubernetescrd
    hosts:
      - host: goldilocks.infrastructure.${domain-name}
        paths:
          - path: /
            type: Prefix
    tls:
      - secretName: goldilocks-cert
        hosts:
        - goldilocks.infrastructure.${domain-name}
