apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: ${namespace}
spec:
  secretName: minio-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: minio-cert
  dnsNames:
  - 'minio.infrastructure.${domain-name}'
  - 'console.minio.infrastructure.${domain-name}'
