apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: ${namespace}
spec:
  mode: deployment # This configuration is omittable.
  ports:
    - name: otel-metrics
      port: 8889
  podAnnotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8889"
    prometheus.io/scrape: "true"
    component: otel-connector
  config: |
    ${configuration}
