apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: ${namespace}
spec:
  mode: deployment # This configuration is omittable.
  ports:
    - name: otel-metrics
      port: 8889
  podAnnotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8889"
    prometheus.io/scrape: "true"
    component: otel-connector
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    processors:
      batch:
    extensions:
      health_check:
      pprof:
      zpages:
    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: "jaeger-collector.jaeger.svc.cluster.local:14250"
        tls:
          insecure: true
      otlp:
        endpoint: "tempo.tempo.svc.cluster.local:4317"
        tls:
          insecure: true
      loki:
        endpoint: "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
        format: json
        labels:
          attributes:
            source: ""
            severity: ""
            "[Scope.1]:ConnectionId": "connectionId"
            "[Scope.2]:RequestId": "requestId"
            "[Scope.2]:RequestPath": "requestPath"
            "[Scope.3]:ActionId": "actionId"
            "[Scope.3]:ActionName": "actionName"
            "[Scope.4]:Id": "id"
            dotnet.ilogger.category: "dotnet_ilogger_category"
          resource:
            k8s.cluster.name: "k8s_cluster_name"
            container.name: "container_name"
            host.name: "hostname"
            http.status_code: "http_status_code"
            service.name: "app"
            service.instance.id: "instance_id"
            service.version: "service_version"
            telemetry.sdk.language: "telemetry_sdk_language"
            telemetry.sdk.name: "telemetry_sdk_name"
            telemetry.sdk.version: "telemetry_sdk_version"
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: "external"
    service:
      extensions: [health_check,pprof,zpages]
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp,jaeger]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          exporters: [loki,logging]
