mssql:
  enabled: true
  MSSQL_MEMORY_LIMIT_MB: 512
  pvc:
    StorageClass: "${storageclass}"
    userdbaccessMode: ReadWriteOnce
    userdbsize: 1Gi
    userlogaccessMode: ReadWriteOnce
    userlogsize: 1Gi
    tempdbaccessMode: ReadWriteOnce
    tempsize: 500Mi
    mssqldataaccessMode: ReadWriteOnce
    mssqldbsize: 500Mi
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
resources:
  limits:
    memory: 500Mi
  requests:
    memory: 250Mi