apiVersion: v1
kind: Secret
metadata:
  name: forward-auth-secret
  namespace: ${namespace}
type: Opaque
data:
  forward_client_id: "${forward_client_id}"
  forward_client_secret: "${forward_client_secret}"