apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: devinfra
build:
profiles:
- name: minikube
  activation:
    - kubeContext: minikube
- name: docker-desktop
  activation:
    - kubeContext: docker-desktop
- name: kind
  activation:
    - kubeContext: kind-devinfra
      command: dev
deploy:
  kubectl:
    manifests:
    - 'traefik/crds/certs/*.yaml'
    - 'traefik/crds/routes/*.yaml'
    - 'traefik/crds/*.yaml'
    - 'jaeger/crds/*.yaml'
    - 'prometheus/crds/*.yaml'
    - 'loki/crds/*.yaml'
    - 'coredns/*.yaml'
    - 'elasticsearch/crds/*.yaml'
  helm:
    releases:
    - name: consul
      # repo: https://helm.releases.hashicorp.com
      remoteChart: hashicorp/consul
      namespace: infrastructure
      version: 0.31.1
      wait: true
      # createNamespace: true
      valuesFiles:
      - consul/consul-values.yaml

    - name: traefik
      # repo: https://helm.traefik.io/traefik
      remoteChart: traefik/traefik
      namespace: infrastructure
      version: 9.19.1
      valuesFiles:
      - traefik/traefik-values.yaml

    - name: prometheus
      # repo: https://prometheus-community.github.io/helm-charts
      remoteChart: prometheus-community/kube-prometheus-stack
      namespace: infrastructure
      version: 16.0.1
      valuesFiles:
      - prometheus/prometheus-values.yaml

    - name: loki
      # repo: https://grafana.github.io/helm-charts
      remoteChart: grafana/loki
      namespace: infrastructure
      version: 2.5.0
      valuesFiles:
      - loki/loki-values.yaml

    - name: promtail
      # repo: https://grafana.github.io/helm-charts
      remoteChart: grafana/promtail
      namespace: infrastructure
      version: 3.5.1
      valuesFiles:
      - loki/promtail-values.yaml

    - name: jaeger-operator
      # repo: https://jaegertracing.github.io/helm-charts
      remoteChart: jaegertracing/jaeger-operator
      namespace: infrastructure
      version: 2.21.1
      valuesFiles:
      - jaeger/jaeger-values.yaml

    # - name: seq
    #   # repo: https://helm.datalust.co
    #   remoteChart: datalust/seq
    #   namespace: infrastructure
    #   version: 2021.2.5647
    #   valuesFiles:
    #   - seq/seq-values.yaml

    # - name: fluent
    #   # repo: https://fluent.github.io/helm-charts
    #   remoteChart: fluent/fluent-bit
    #   namespace: infrastructure
    #   version: 0.15.11
    #   valuesFiles:
    #   - seq/fluent-values.yaml

    - name: elastic-operator
      # repo:  https://helm.elastic.co
      remoteChart: elastic/eck-operator
      namespace: infrastructure
      version: 1.6.0
      valuesFiles:
      - elasticsearch/eck-values.yaml
