apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth-deployment
  namespace: ${namespace}
  annotations:
    runterrascan.io/skip: "[{\"rule\": \"AC-K8-NS-PO-H-0117\", \"comment\": \"Demo container\"},{\"rule\": \"AC_K8S_0069\", \"comment\": \"No other tag available\"},{\"rule\": \"AC_K8S_0068\", \"comment\": \"No other tag available\"}]"
spec:
  selector:
    matchLabels:
      app: traefik-forward-auth
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      containers:
      - name: traefik-forward-auth
        image: thomseddon/traefik-forward-auth:latest
        ports:
          - name: http
            containerPort: 4181
            protocol: TCP
        volumeMounts:
          - name: certs
            mountPath: /etc/ssl/certs/ca.crt
            subPath: ca.crt
            readOnly: true
          - name: certs
            mountPath: /etc/ssl/certs/tls.crt
            subPath: tls.crt
            readOnly: true
          - name: certs
            mountPath: /etc/ssl/certs/tls.key
            subPath: tls.key
            readOnly: true
        env:
        - name: CONFIG
          value: "/config"
        - name: DEFAULT_PROVIDER
          value: "oidc"
        - name: DEFAULT_ACTION
          value: "auth"
        - name: PROVIDERS_OIDC_ISSUER_URL
          value: "https://login.${domain-name}/auth/realms/k8slocal"
        - name: PROVIDERS_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: forward-auth-secret
              key: forward_client_id
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: forward-auth-secret
              key: forward_client_secret
        - name: "SECRET"
          value: "SomeRandomSecret"
        - name: "INSECURE_COOKIE"
          value: "false"
        - name: "AUTH_HOST"
          value: "auth.${domain-name}"
        - name: "URL_PATH"
          value: "/_oauth"
        - name: "COOKIE_DOMAIN"
          value: "${domain-name}"
        - name: "COOKIE_NAME"
          value: "_forward_auth"
        - name: "CSRF_COOKIE_NAME"
          value: "_forward_auth_csrf"
        - name: "LOG_LEVEL"
          value: "debug"
        - name: "LIFETIME"
          value: "43200"
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
      volumes:
        - name: certs
          secret:
            secretName: keycloak-cert
            items:
            - key: ca.crt
              path: ca.crt
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
