apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    # consul:53 {
    #   log
    #   errors
    #   cache 30
    #   forward . 10.96.153.138
    # }
    .:53 {
        errors
        health {
          lameduck 5s
        }
        rewrite name login.k8s.local identityserver4-admin-identity.identityserver4-admin.svc.cluster.local
        rewrite name admin.login.k8s.local identityserver4-admin-admin.identityserver4-admin.svc.cluster.local
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
