seed:
  defaultAdmin:
    password: Password_123
    email: your.email@gmail.com

certificates:
  certManager:
    enabled: true
    issuerRef:
      name: selfsigned-ca-issuer
      kind: ClusterIssuer

admin:
  protocol: https
  domainName: admin.login.k8s.local
  ssl:
    enabled: true
    secretName: identityserver4-cert-admin
  service:
    type: ClusterIP
    port: 443
  podAnnotations:
      "linkerd.io/inject": "enabled"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http@kubernetescrd
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: admin.login.k8s.local
        paths:
        - path: /
          backend:
            serviceName: identityserver4-admin
            servicePort: 443
    tls:
    - secretName: traefik-cert
      hosts:
        - admin.login.k8s.local
identity:
  protocol: https
  domainName: login.k8s.local
  ssl:
    enabled: true
    secretName: identityserver4-cert-identity
  service:
    type: ClusterIP
    port: 443
  podAnnotations:
      "linkerd.io/inject": "enabled"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http@kubernetescrd
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: login.k8s.local
        paths:
        - path: /
          backend:
            serviceName: identityserver4-identity
            servicePort: 443
    tls:
    - secretName: traefik-cert
      hosts:
        - login.k8s.local
api:
  enabled: true
  protocol: https
  domainName: api.login.k8s.local
  ssl:
    enabled: true
    secretName: identityserver4-cert-api
  service:
    type: ClusterIP
    port: 443
  podAnnotations:
      "linkerd.io/inject": "enabled"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http@kubernetescrd
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.login.k8s.local
        paths:
        - path: /
          backend:
            serviceName: identityserver4-api
            servicePort: 443
    tls:
    - secretName: traefik-cert
      hosts:
        - api.login.k8s.local
mssql:
  enabled: true
  sa_password: "Toughpass1!"
  mssql:
    enabled: true
    MSSQL_MEMORY_LIMIT_MB: 512
    pvc:
      StorageClass: "standard"
      userdbaccessMode: ReadWriteOnce
      userdbsize: 1Gi
      userlogaccessMode: ReadWriteOnce
      userlogsize: 1Gi
      tempdbaccessMode: ReadWriteOnce
      tempsize: 500Mi
      mssqldataaccessMode: ReadWriteOnce
      mssqldbsize: 500Mi
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
  resources:
    limits:
      memory: 500Mi
    requests:
      memory: 250Mi