apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oracle-cert
  namespace: ${namespace}
spec:
  secretName: oracle-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: oracle-cert
  dnsNames:
  - 'oracle.infrastructure.${domain-name}'
