apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "testdeploy-foo-ingressroute"
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/foo`)
      kind: Rule
      namespace: infrastructure
      services:
      - name: foo-service
        port: 5678
        path: /
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "testdeploy-bar-ingressroute"
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/bar`)
      kind: Rule
      namespace: infrastructure
      services:
      - name: bar-service
        port: 5678
        path: /
