apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-cert
  namespace: ${namespace}
spec:
  secretName: redis-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: redis-cert
  dnsNames:
  - 'redis.infrastructure.${domain-name}'
