## https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml

# env:
# - name: "FLUENTD_CONF"
#   value: "../../etc/fluent/fluent.conf"
# - name: FLUENT_GELF_HOST
#   value: "seq.${namespace}.svc.cluster.local"
# - name: FLUENT_GELF_PORT
#   value: "12201"
# - name: FLUENT_GELF_PROTOCOL
#   value: "tcp"

rbac:
  create: true
  nodeAccess: true

daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcmachineid
    hostPath: #hack to fake a machine-id on k3s
      path: /etc/hostname
      type: File

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true

service:
  labels:
    app: fluent-bit
  annotations:
    prometheus.io/path: "/api/v1/metrics/prometheus"
    prometheus.io/port: "2020"
    prometheus.io/scrape: "true"

serviceMonitor:
  enabled: true
  namespace: ${namespace}
  interval: 10s
  scrapeTimeout: 10s
  selector:
    prometheus: prometheus
    app: traefik
    release: prometheus

dashboards:
  enabled: true
  labelKey: grafana_dashboard
  annotations:
    k8s-sidecar-target-directory: /tmp/dashboards/Infrastructure
config:
  inputs: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  outputs: |
    [OUTPUT]
        Name                    gelf
        Match                   kube.*
        Host                    ${FLUENT_GELF_HOST}
        Port                    ${FLUENT_GELF_PORT}
        Mode                    ${FLUENT_GELF_PROTOCOL}
        Gelf_Short_Message_Key  log
  customParsers: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   Off
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
        Time_Keep   Off