helm_versions:
  elasticsearch:
    repository:
      name: elastic
      url: https://helm.elastic.co
    chart_name: eck-operator
    chart_version: 2.6.1
  etcd:
    repository:
      name: bitnami
      url: https://charts.bitnami.com/bitnami
    chart_name: etcd
    chart_version: 8.7.3
  redis:
    repository:
      name: bitnami
      url: https://charts.bitnami.com/bitnami
    chart_name: redis
    chart_version: 17.7.2
  vault:
    repository:
      name: hashicorp
      url: https://helm.releases.hashicorp.com
    chart_name: vault
    chart_version: 0.23.0
