apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: ${namespace}
spec:
  interval: 1m0s
  ref:
    branch: ${branch}
  secretRef:
    name: ${namespace}
  url: ${git_url}