apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: ${namespace}
spec:
  interval: 10m0s
  path: ${target_path}
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${namespace}