apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger
spec:
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-port": "6831"
    "consul.hashicorp.com/transparent-proxy": "true"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http@kubernetescrd
    hosts:
      - jaeger.infrastructure.k8s.local
    path: /
    pathType: Prefix
    tls:
      - secretName: jaeger-cert
        hosts:
        - jaeger.infrastructure.k8s.local
  allInOne:
    options:
      query:
        base-path: /jaeger
agent:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/transparent-proxy": "true"
query:
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/transparent-proxy": "true"
