receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
processors:
  batch:
  attributes:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: container.name, host.name, service.name, service.version, http_status_code
  resource:
    attributes:
    - action: insert
      key: loki.resource.labels
      value: container.name, host.name, service.name, service.version, telemetry.sdk.language, telemetry.sdk.name, telemetry.sdk.version
extensions:
  health_check:
  pprof:
  zpages:
exporters:
  logging:
    loglevel: debug
#%{ if install_jaeger == true }
  jaeger:
    endpoint: "${jaeger_endpoint}"
    tls:
      insecure: true
#%{ endif }
  otlp:
    endpoint: "tempo.tempo.svc.cluster.local:4317"
    tls:
      insecure: true
#%{ if install_loki == true }
  loki:
    endpoint: "${loki_endpoint}"
#%{ endif }
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: "otelgateway"
service:
  extensions: [health_check,pprof,zpages]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
#%{ if install_jaeger == true }
      exporters: [otlp,jaeger]
#%{ else }
      exporters: [otlp]
#%{ endif }
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
#%{ if install_loki == true }
      exporters: [loki,logging]
#%{ else }
      exporters: [logging]
#%{ endif }