apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis
  namespace: ${namespace}
spec:
  entryPoints:
    - redis
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - name: redis-master
      port: 6379
