apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-es
  namespace: infrastructure
spec:
  version: 7.12.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          consul.hashicorp.com/connect-service: "elastic-es"
          consul.hashicorp.com/connect-inject: "true"
          consul.hashicorp.com/connect-service-port: "http"
      spec:
        automountServiceAccountToken: true
        serviceAccount: elastic-es