apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: ${namespace}
spec:
  mode: deployment # This configuration is omittable.
  config: |
    ${configuration}