apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: es-cert
  namespace: ${namespace}
spec:
  secretName: es-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: es-cert
  dnsNames:
  - 'es.infrastructure.${domain-name}'
  - 'kibana.infrastructure.${domain-name}'
