apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localstack-cert
  namespace: ${namespace}
spec:
  secretName: localstack-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: localstack-cert
  dnsNames:
  - 'localstack.infrastructure.${domain-name}'
