# Override of: https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/values.yaml

dashboard:
  enforcedHostRegexp: "^linkerd\\.infrastructure\\.k8s\\.local$"
#%{ if metrics_external == true }
prometheusUrl: http://prometheus-kube-prometheus-prometheus.prometheus:9090
#%{ endif }
prometheus:
  enabled: ${!metrics_external == true}
# grafana:
#   enabled: false
#%{ if tracing == true }
jaegerUrl: jaeger-query.jaeger:16686
#%{ endif }
