apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: prometheus
spec:
  secretName: prometheus-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: prometheus-cert
  dnsNames:
  - 'prometheus.infrastructure.k8s.local'
  - 'grafana.infrastructure.k8s.local'
