
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  traefik
  namespace: traefik
  labels:
    app: traefik
    release: prometheus
spec:
  jobLabel: traefik-metrics
  selector:
    matchLabels:
      app: traefik
  namespaceSelector:
    matchNames:
    - traefik
  endpoints:
  - port: metrics
    path: /metrics
