apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: ${namespace}
spec:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 512Mi

  # replicas: 1
  rabbitmq:
    envConfig: |
      RABBITMQ_LOGS=""
    additionalConfig: |
      default_user=guest
      default_pass=guest
      loopback_users.guest = false
      log.console = true
      log.console.level = debug
      log.console.formatter = json
      log.console.formatter.json.field_map = verbosity:v time msg domain file line pid level:-
      log.console.formatter.json.verbosity_map = debug:7 info:6 notice:5 warning:4 error:3 critical:2 alert:1 emergency:0
      log.console.formatter.time_format = epoch_usecs
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel