# Override of : https://github.com/bitnami/charts/blob/master/bitnami/metrics-server/values.yaml

extraArgs:
  kubelet-insecure-tls: true
  kubelet-preferred-address-types: InternalIP
apiService:
  create: true