apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongodb
  namespace: ${namespace}
spec:
  entryPoints:
    - mongodb
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - name: mongodb
      port: 27017
