apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-cert
  namespace: ${namespace}
spec:
  secretName: mongodb-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: mongodb-cert
  dnsNames:
  - 'mongodb.infrastructure.${domain-name}'
