apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-cert
  namespace: ${namespace}
spec:
  secretName: etcd-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: etcd-cert
  dnsNames:
  - 'etcd.infrastructure.${domain-name}'
