apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert
  namespace: ${namespace}
spec:
  secretName: whoami-cert
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
  commonName: whoami-cert
  dnsNames:
  - 'whoami1.${domain-name}'
