name: Build

on: [push, pull_request]

permissions:
  contents: write
  discussions: write

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: src

      - name: Create temp files for terraform validation
        run: |
          touch src/certs/cacerts.crt
          touch src/certs/cacerts.key
          touch src/terraform/.env
          echo GITHUB_OWNER=somebody >> src/terraform/.env
          echo GITHUB_TOKEN=sometoken >> src/terraform/.env
          echo ORACLE_EMAIL=someemail >> src/terraform/.env
          echo ORACLE_PASSWORD=somepassword >> src/terraform/.env

      - name: terraform validate src-clusters-k3d
        uses: dflook/terraform-validate@v1
        with:
          path: src/clusters/k3d

      - name: terraform validate src-clusters-kind
        uses: dflook/terraform-validate@v1
        with:
          path: src/clusters/kind

      - name: terraform validate src-terraform
        uses: dflook/terraform-validate@v1
        with:
          path: src/terraform

  release:
    runs-on: ubuntu-latest
    name: Release
    needs: [validate]
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          discussion_category_name: Announcements
          append_body: true
