on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: src

      - name: terraform validate src-clusters-k3d
        uses: dflook/terraform-validate@v1
        with:
          path: src/clusters/k3d

      - name: terraform validate src-clusters-kind
        uses: dflook/terraform-validate@v1
        with:
          path: src/clusters/kind


      - name: terraform validate src-terraform
        uses: dflook/terraform-validate@v1
        with:
          path: src/terraform