name: Check Dependencies

on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/check-dependencies.yml'
    - 'src/terraform/dependencies.yaml'
  schedule:
    # Runs "At 00:00 on Saturday." (see https://crontab.guru)
    - cron: '0 0 * * 6'

permissions:
  contents: write

jobs:
  helm-charts:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm Dependencies
        uses: hckops/actions/helm-dependencies-action@main
        with:
          user-email: "bravecobra-bot@users.noreply.github.com"
          user-name: "bravecobra-bot"
          config-path: src/terraform/dependencies.yml
          default-branch: feature/helm_versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}