name: E2E Databases

on:
  pull_request:
    paths:
      - 'src/terraform/versions-databases.yaml'

jobs:
  call_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Call E2E Workflow
      uses: ./.github/workflows/e2e.yml
      with:
        install_DBs: true
