name: tfsec
on:
  push:
    branches:
      - master
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: tfsec
        uses: dansanabria/tfsec-sarif-action@fix-url-typo
        with:
          tfsec_version: v1.8.0
          sarif_file: tfsec.sarif
          working_directory: src/terraform
          tfvars_file: src/tests/k3s/terraform.tfvars
          tfsec_args: --debug

      - name: Output SARIF file
        run: |
          cat tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
